import { useEffect, useMemo, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { getScanStatus, stopScan, downloadScanReport, getCheckers, updateScanFeedback, getSkillContent, triggerFpReview, stopFpReview, getFpReview, getFpReviewSkill, getSkillReports, retryIncompleteScan } from "../api/client";
import type { FpReviewJob, IndexStatus, ScanItemStatus, ScanStatus as ScanStatusType, ScanEvent, CheckerInfo, SkillReport, OpenCodePoolStatus } from "../types";
import { useScanSSE } from "../hooks/useScanSSE";
import type { ScanSSEHandlers, SSEStateSetters } from "../hooks/useScanSSE";
import VulnerabilityList from "./VulnerabilityList";
import FeedbackManager from "./FeedbackManager";

const MAX_LOG_LINES = 500;
const AGENT_DISCONNECT_ERROR = "Agent 断开连接";
const FINAL_USER_VERDICTS = new Set(["confirmed", "false_positive"]);

const PHASES = [
  { key: "init", label: "初始化" },
  { key: "static_analysis", label: "静态分析" },
  { key: "auditing", label: "AI 审计" },
  { key: "complete", label: "完成" },
] as const;

function statusToPhaseIndex(status: ScanItemStatus): number {
  if (status === "pending") return 0;
  if (status === "analyzing") return 1;
  if (status === "auditing") return 2;
  return 3;
}

function isAgentDisconnectError(message: string | null | undefined): boolean {
  return !!message && message.includes(AGENT_DISCONNECT_ERROR);
}

function hasFinalUserVerdict(vuln: { user_verdict?: string | null }): boolean {
  return FINAL_USER_VERDICTS.has(vuln.user_verdict || "");
}

interface Props {
  scanId: string;
  onBack: () => void;
}

export default function ScanStatus({ scanId, onBack }: Props) {
  const [scan, setScan] = useState<ScanStatusType | null>(null);
  const [stopping, setStopping] = useState(false);
  const [retryingIncomplete, setRetryingIncomplete] = useState(false);
  const [downloadingReport, setDownloadingReport] = useState(false);
  const [logOpen, setLogOpen] = useState(false);
  const [modelPoolOpen, setModelPoolOpen] = useState(false);
  const [lastSeenEvents, setLastSeenEvents] = useState(0);
  const logRef = useRef<HTMLDivElement>(null);

  // Feedback panel state
  const [feedbackOpen, setFeedbackOpen] = useState(false);
  const [checkers, setCheckers] = useState<CheckerInfo[]>([]);
  const [selectedFeedbackIds, setSelectedFeedbackIds] = useState<Set<string> | null>(null);

  // SKILL preview state
  const [skillOpen, setSkillOpen] = useState(false);
  const [skillType, setSkillType] = useState<string | null>(null);
  const [skillContent, setSkillContent] = useState("");
  const [skillLoading, setSkillLoading] = useState(false);

  // Markdown reports generated by user-created SKILLs
  const [reportsOpen, setReportsOpen] = useState(false);
  const [reports, setReports] = useState<SkillReport[]>([]);
  const [reportsLoading, setReportsLoading] = useState(false);
  const [activeReportIndex, setActiveReportIndex] = useState(0);

  // FP review state
  const [fpReview, setFpReview] = useState<FpReviewJob | null>(null);
  const [fpReviewLoading, setFpReviewLoading] = useState(false);
  const [fpReviewStopping, setFpReviewStopping] = useState(false);

  // Code indexing progress
  const [indexStatus, setIndexStatus] = useState<IndexStatus | null>(null);

  const isRunning = scan && (scan.status === "pending" || scan.status === "analyzing" || scan.status === "auditing");
  const isDone = scan && (scan.status === "complete" || scan.status === "error" || scan.status === "cancelled");

  useEffect(() => {
    getCheckers().then(setCheckers).catch(() => {});
  }, []);

  // Initial full-state hydration on mount
  useEffect(() => {
    getScanStatus(scanId)
      .then((data) => {
        setScan(data);
        if (selectedFeedbackIds === null && data.feedback_ids) {
          setSelectedFeedbackIds(new Set(data.feedback_ids));
        }
      })
      .catch(() => {});
    getFpReview(scanId)
      .then(setFpReview)
      .catch(() => {});
  }, [scanId]);

  // SSE event handlers — update state incrementally
  const sseHandlers = useMemo<ScanSSEHandlers>(() => ({
    onScanStatus: (data) => {
      setScan((prev) => {
        if (!prev) return prev;
        const patch: Partial<ScanStatusType> = {};
        if (data.status != null) patch.status = data.status as ScanItemStatus;
        if (data.progress != null) patch.progress = data.progress;
        if (data.total_candidates != null) patch.total_candidates = data.total_candidates;
        if (data.processed_candidates != null) patch.processed_candidates = data.processed_candidates;
        if (data.static_total_files != null) patch.static_total_files = data.static_total_files;
        if (data.static_scanned_files != null) patch.static_scanned_files = data.static_scanned_files;
        if (data.static_analysis_done != null) patch.static_analysis_done = data.static_analysis_done;
        if (data.opencode_pool !== undefined) patch.opencode_pool = data.opencode_pool;
        return { ...prev, ...patch };
      });
    },
    onScanVulnerability: (data) => {
      setScan((prev) => {
        if (!prev) return prev;
        const vulns = [...prev.vulnerabilities];
        vulns[data.index] = data.vulnerability;
        return { ...prev, vulnerabilities: vulns };
      });
    },
    onScanEvent: (data) => {
      setScan((prev) => {
        if (!prev) return prev;
        const events = [...prev.events, data.event].slice(-MAX_LOG_LINES);
        return { ...prev, events };
      });
    },
    onScanFinish: (data) => {
      setScan((prev) =>
        prev ? { ...prev, status: data.status as ScanItemStatus, error_message: data.error_message } : prev,
      );
    },
    onFpReviewStarted: (data) => {
      setFpReview({
        review_id: data.review_id,
        scan_id: scanId,
        status: data.status,
        total: data.total,
        processed: 0,
        current_vuln_index: null,
        results: [],
        error_message: null,
        created_at: new Date().toISOString(),
      });
    },
    onFpReviewProgress: (data) => {
      setFpReview((prev) => {
        if (!prev || prev.review_id !== data.review_id) return prev;
        return {
          ...prev,
          status: "running",
          processed: data.processed,
          current_vuln_index: data.vuln_index,
          total: data.total,
        };
      });
    },
    onFpReviewStageOutput: (data) => {
      setFpReview((prev) => {
        if (!prev || prev.review_id !== data.review_id) return prev;
        const results = [...prev.results];
        const existingIndex = results.findIndex((result) => result.vuln_index === data.vuln_index);
        if (existingIndex >= 0) {
          const existing = results[existingIndex];
          results[existingIndex] = {
            ...existing,
            stage_outputs: {
              ...(existing.stage_outputs ?? {}),
              [data.stage]: data.markdown,
            },
          };
        } else {
          results.push({
            vuln_index: data.vuln_index,
            verdict: "tp",
            severity: "low",
            reason: "",
            vulnerability_report: "",
            stage_outputs: { [data.stage]: data.markdown },
            created_at: new Date().toISOString(),
          });
        }
        return { ...prev, status: "running", results };
      });
    },
    onFpReviewResult: (data) => {
      setFpReview((prev) => {
        if (!prev || prev.review_id !== data.review_id) return prev;
        const existing = prev.results.find((result) => result.vuln_index === data.vuln_index);
        const newResult = {
          vuln_index: data.vuln_index,
          verdict: data.verdict,
          severity: data.severity,
          reason: data.reason,
          vulnerability_report: data.vulnerability_report ?? "",
          stage_outputs: {
            ...(existing?.stage_outputs ?? {}),
            ...(data.stage_outputs ?? {}),
          },
          created_at: new Date().toISOString(),
        };
        return {
          ...prev,
          status: "running",
          results: [
            ...prev.results.filter((result) => result.vuln_index !== data.vuln_index),
            newResult,
          ],
        };
      });
    },
    onFpReviewFinish: (data) => {
      setFpReview((prev) => {
        if (!prev || prev.review_id !== data.review_id) return prev;
        return { ...prev, status: data.status, error_message: data.error_message, current_vuln_index: null };
      });
    },
    onIndexStatus: (data) => {
      setIndexStatus(data);
    },
  }), [scanId]);

  const sseStateSetters = useMemo<SSEStateSetters>(() => ({
    setScan,
    setFpReview,
    setIndexStatus,
  }), []);

  useScanSSE(scanId, sseHandlers, sseStateSetters);

  const handleFpReview = async () => {
    setFpReviewLoading(true);
    try {
      const started = await triggerFpReview(scanId);
      setFpReview({
        review_id: started.review_id,
        scan_id: scanId,
        status: started.status ?? "running",
        total: started.total ?? 0,
        processed: started.processed ?? 0,
        current_vuln_index: null,
        results: [],
        error_message: null,
        created_at: new Date().toISOString(),
      });
    } catch (err: unknown) {
      const msg = err && typeof err === "object" && "response" in err
        ? (err as { response: { data: { detail: string } } }).response?.data?.detail
        : "触发失败";
      alert(`AI去误报失败：${msg || "未知错误"}`);
    } finally {
      setFpReviewLoading(false);
    }
  };

  const handleStopFpReview = async () => {
    setFpReviewStopping(true);
    try {
      await stopFpReview(scanId);
      const job = await getFpReview(scanId);
      setFpReview(job);
    } catch (err: unknown) {
      const msg = err && typeof err === "object" && "response" in err
        ? (err as { response: { data: { detail: string } } }).response?.data?.detail
        : "停止失败";
      alert(`停止AI复核失败：${msg || "未知错误"}`);
    } finally {
      setFpReviewStopping(false);
    }
  };

  const handleStop = async () => {
    setStopping(true);
    try {
      await stopScan(scanId);
    } catch {
      setStopping(false);
    }
  };

  const handleRetryIncomplete = async () => {
    setRetryingIncomplete(true);
    try {
      await retryIncompleteScan(scanId);
      const next = await getScanStatus(scanId);
      setScan(next);
    } catch (err: unknown) {
      const msg = err && typeof err === "object" && "response" in err
        ? (err as { response: { data: { detail: string } } }).response?.data?.detail
        : "续扫失败";
      alert(`续扫未完成候选失败：${msg || "未知错误"}`);
    } finally {
      setRetryingIncomplete(false);
    }
  };

  const handleDownloadReport = async () => {
    if (!scan) return;
    setDownloadingReport(true);
    try {
      const blob = await downloadScanReport(scan.scan_id);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `report-${scan.scan_id}.csv`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.setTimeout(() => URL.revokeObjectURL(url), 0);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "未知错误";
      alert(`下载 CSV 失败：${msg}`);
    } finally {
      setDownloadingReport(false);
    }
  };

  // Handle feedback selection change — update backend and refresh skills
  const handleFeedbackChange = async (ids: Set<string>) => {
    setSelectedFeedbackIds(ids);
    setScan((prev) => prev ? { ...prev, feedback_ids: [...ids] } : prev);
    try {
      await updateScanFeedback(scanId, [...ids]);
      // Refresh SKILL preview if it's currently open
      if (skillOpen && skillType) {
        const content = skillType === "__fp_review__"
          ? await getFpReviewSkill(scanId)
          : await getSkillContent(scanId, skillType);
        setSkillContent(content);
      }
    } catch {
      // ignore
    }
  };

  const addSelectedFeedbackIds = async (feedbackIds: string[]) => {
    if (feedbackIds.length === 0) return;
    const next = new Set(selectedFeedbackIds ?? scan?.feedback_ids ?? []);
    for (const id of feedbackIds) next.add(id);
    await handleFeedbackChange(next);
  };

  const removeSelectedFeedbackIds = async (feedbackIds: string[]) => {
    if (feedbackIds.length === 0) return;
    const next = new Set(selectedFeedbackIds ?? scan?.feedback_ids ?? []);
    for (const id of feedbackIds) next.delete(id);
    setSelectedFeedbackIds(next);
    setScan((prev) => prev ? { ...prev, feedback_ids: [...next] } : prev);
  };

  const loadSkill = async (vulnType: string) => {
    setSkillType(vulnType);
    setSkillLoading(true);
    try {
      const content = await getSkillContent(scanId, vulnType);
      setSkillContent(content);
    } catch {
      setSkillContent("加载失败");
    } finally {
      setSkillLoading(false);
    }
  };

  const loadFpReviewSkill = async () => {
    setSkillType("__fp_review__");
    setSkillLoading(true);
    try {
      const content = await getFpReviewSkill(scanId);
      setSkillContent(content);
    } catch {
      setSkillContent("加载失败");
    } finally {
      setSkillLoading(false);
    }
  };

  const loadSkillReports = async () => {
    setReportsOpen(true);
    setReportsLoading(true);
    try {
      const next = await getSkillReports(scanId);
      setReports(next);
      setActiveReportIndex(0);
    } catch {
      setReports([]);
    } finally {
      setReportsLoading(false);
    }
  };

  // Compute log event count for scroll/unseen tracking
  const logEventCount = scan?.events.length ?? 0;

  // Auto-scroll log
  useEffect(() => {
    if (logRef.current && logOpen) {
      logRef.current.scrollTop = logRef.current.scrollHeight;
    }
  }, [logEventCount, logOpen]);

  // Track unseen events
  useEffect(() => {
    if (logOpen) {
      setLastSeenEvents(logEventCount);
    }
  }, [logOpen, logEventCount]);

  if (!scan) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex items-center justify-center">
        <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
      </div>
    );
  }

  const activePhase = statusToPhaseIndex(scan.status);
  const pct = Math.round(scan.progress * 100);
  const allLogEvents = scan.events;
  const truncated = allLogEvents.length > MAX_LOG_LINES;
  const logEvents = truncated ? allLogEvents.slice(-MAX_LOG_LINES) : allLogEvents;
  const unseenCount = allLogEvents.length - lastSeenEvents;
  const feedbackCount = selectedFeedbackIds?.size ?? scan.feedback_ids?.length ?? 0;
  const agentDisconnectError = isAgentDisconnectError(scan.error_message);
  const staleAgentDisconnectError = scan.status === "cancelled" && agentDisconnectError && !!scan.agent_online;
  const visibleErrorMessage = staleAgentDisconnectError ? null : scan.error_message;
  const currentFpReviewIndex = fpReview?.current_vuln_index ?? null;
  const currentFpReviewTarget =
    currentFpReviewIndex !== null && currentFpReviewIndex >= 0
      ? scan.vulnerabilities[currentFpReviewIndex]
      : undefined;
  const isFpReviewing = fpReview?.status === "running" || fpReview?.status === "pending";
  const reportCheckers = checkers.filter(
    (checker) => scan.scan_items.includes(checker.name) && checker.result_mode === "markdown_reports",
  );
  const hasReportModeSkill = reportCheckers.length > 0 || (scan.skill_reports?.length ?? 0) > 0;
  const displayedReports = reports.length > 0 ? reports : (scan.skill_reports ?? []);
  const activeReport = displayedReports[activeReportIndex] ?? displayedReports[0];
  const retryableCount = scan.vulnerabilities.filter(
    (v) => !hasFinalUserVerdict(v) && (v.ai_verdict === "timeout" || v.ai_verdict === "no_result"),
  ).length || scan.retryable_candidates_count || 0;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 flex flex-col">
      {/* Top bar */}
      <div className="bg-slate-800/80 backdrop-blur border-b border-slate-700 px-6 py-4">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-4">
            <button
              onClick={onBack}
              className="text-sm text-slate-400 hover:text-slate-200 transition-colors flex items-center gap-1"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
              返回
            </button>
            <h1 className="text-lg font-bold text-white">OpenDeepHole</h1>
            <span className="text-sm text-slate-400">
              {scan.status === "cancelled"
                ? (agentDisconnectError ? (scan.agent_online ? "扫描已中断" : "Agent 断开，已中断") : "已取消")
                : isDone ? "扫描完成" : "扫描中..."}
            </span>
            {scan.agent_name && (
              <span className="flex items-center gap-1.5 text-sm text-slate-400 border-l border-slate-600 pl-4">
                <span
                  className={`w-2 h-2 rounded-full flex-shrink-0 ${
                    scan.agent_online ? "bg-green-400" : "bg-slate-500"
                  }`}
                />
                Agent: {scan.agent_name}
                {!scan.agent_online && (
                  <span className="text-xs text-slate-500">(离线)</span>
                )}
              </span>
            )}
          </div>
          <div className="flex items-center gap-3">
            {/* Feedback button with count badge */}
            <button
              onClick={() => setFeedbackOpen(true)}
              className="px-3 py-1.5 text-sm font-medium text-slate-300 border border-slate-600 rounded-lg hover:bg-slate-700 transition-colors flex items-center gap-1.5"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
              </svg>
              误报屏蔽规则
              {feedbackCount > 0 && (
                <span className="bg-blue-500 text-white text-xs rounded-full px-1.5 py-0.5 min-w-[1.25rem] text-center">
                  {feedbackCount}
                </span>
              )}
            </button>
            <button
              onClick={() => {
                setSkillOpen(true);
                if (!skillType && scan.scan_items.length > 0) {
                  loadSkill(scan.scan_items[0]);
                }
              }}
              className="px-3 py-1.5 text-sm font-medium text-slate-300 border border-slate-600 rounded-lg hover:bg-slate-700 transition-colors flex items-center gap-1.5"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
              </svg>
              SKILL 预览
            </button>
            <button
              onClick={() => setModelPoolOpen(true)}
              className="px-3 py-1.5 text-sm font-medium text-cyan-300 border border-cyan-500/40 rounded-lg hover:bg-cyan-500/10 transition-colors flex items-center gap-1.5"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 19V5m0 14h16M8 15V9m4 6V7m4 8v-4" />
              </svg>
              模型看板
              {(scan.opencode_pool?.global_running ?? 0) > 0 && (
                <span className="text-xs text-cyan-100">{scan.opencode_pool?.global_running}</span>
              )}
            </button>
            {hasReportModeSkill && (
              <button
                onClick={loadSkillReports}
                className="px-3 py-1.5 text-sm font-medium text-purple-300 border border-purple-500/40 rounded-lg hover:bg-purple-500/10 transition-colors flex items-center gap-1.5"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                SKILL 报告
                {(scan.skill_reports?.length ?? 0) > 0 && (
                  <span className="text-xs text-purple-200">{scan.skill_reports.length}</span>
                )}
              </button>
            )}
            {(() => {
              const confirmedVulns = scan.vulnerabilities.filter(
                (v) => (v.ai_verdict === "confirmed" || (!v.ai_verdict && v.confirmed)) && !hasFinalUserVerdict(v)
              ).length;
              const canTrigger = confirmedVulns > 0;
              const isReviewing = fpReview?.status === "running" || fpReview?.status === "pending";
              return (
                <>
                  <button
                    onClick={handleFpReview}
                    disabled={!canTrigger || fpReviewLoading || !!isReviewing}
                    className="px-3 py-1.5 text-sm font-medium text-amber-400 border border-amber-500/50 rounded-lg hover:bg-amber-500/10 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center gap-1.5"
                    title={!canTrigger ? "需要存在 LLM 正报才可使用" : "使用 AI 对已确认漏洞逐条进行误报复核"}
                  >
                    {isReviewing ? (
                      <>
                        <div className="w-3 h-3 border border-amber-500/30 border-t-amber-400 rounded-full animate-spin" />
                        复核中 {fpReview!.processed}/{fpReview!.total}
                      </>
                    ) : fpReviewLoading ? (
                      <>
                        <div className="w-3 h-3 border border-amber-500/30 border-t-amber-400 rounded-full animate-spin" />
                        启动中...
                      </>
                    ) : (
                      <>
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        AI去误报
                        {fpReview?.status === "complete" && (
                          <span className="text-xs text-green-400 ml-0.5">✓</span>
                        )}
                        {fpReview?.status === "cancelled" && (
                          <span className="text-xs text-amber-300 ml-0.5">已停止</span>
                        )}
                      </>
                    )}
                  </button>
                  {isReviewing && (
                    <button
                      onClick={handleStopFpReview}
                      disabled={fpReviewStopping}
                      className="px-3 py-1.5 text-sm font-medium text-red-400 border border-red-500/50 rounded-lg hover:bg-red-500/10 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                      title="停止当前AI去误报复核"
                    >
                      {fpReviewStopping ? "停止中..." : "停止复核"}
                    </button>
                  )}
                </>
              );
            })()}
            {isDone && (
              <>
                {retryableCount > 0 && (
                  <button
                    onClick={handleRetryIncomplete}
                    disabled={retryingIncomplete || !scan.agent_online}
                    title={!scan.agent_online ? "Agent 离线，无法续扫" : `续扫 ${retryableCount} 个未完成候选`}
                    className="px-3 py-1.5 text-sm font-medium text-amber-300 border border-amber-500/50 rounded-lg hover:bg-amber-500/10 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                  >
                    {retryingIncomplete ? "启动中..." : `续扫未完成 ${retryableCount}`}
                  </button>
                )}
              </>
            )}
            {isDone && (
              <button
                onClick={handleDownloadReport}
                disabled={downloadingReport}
                className="px-3 py-1.5 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 disabled:cursor-not-allowed rounded-lg transition-colors"
              >
                {downloadingReport ? "下载中..." : "下载 CSV"}
              </button>
            )}
            {isRunning && (
              <button
                onClick={handleStop}
                disabled={stopping}
                className="px-3 py-1.5 text-sm font-medium text-red-400 border border-red-500/50 rounded-lg hover:bg-red-500/10 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {stopping ? "停止中..." : "停止扫描"}
              </button>
            )}
          </div>
        </div>

        {/* Stepper + Progress */}
        <div className="flex items-center gap-6">
          {/* Phase stepper */}
          <div className="flex items-center flex-shrink-0">
            {PHASES.map((phase, i) => (
              <div key={phase.key} className="flex items-center">
                <div className="flex flex-col items-center">
                  <div
                    className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-colors ${
                      i < activePhase
                        ? "bg-green-500 text-white"
                        : i === activePhase
                          ? "bg-blue-500 text-white ring-2 ring-blue-500/30"
                          : "bg-slate-600 text-slate-400"
                    }`}
                  >
                    {i < activePhase ? "\u2713" : i + 1}
                  </div>
                  <span
                    className={`text-xs mt-1 whitespace-nowrap ${
                      i <= activePhase ? "text-slate-300 font-medium" : "text-slate-500"
                    }`}
                  >
                    {phase.label}
                  </span>
                </div>
                {i < PHASES.length - 1 && (
                  <div
                    className={`w-8 h-0.5 mx-1.5 mt-[-1rem] ${
                      i < activePhase ? "bg-green-500" : "bg-slate-600"
                    }`}
                  />
                )}
              </div>
            ))}
          </div>

          {/* Dual progress bars */}
          <div className="flex-1 min-w-0 space-y-2">
            {/* 代码索引进度条 */}
            {indexStatus && indexStatus.status === "parsing" && scan.static_total_files === 0 && (
              <div>
                <div className="flex justify-between text-xs text-slate-400 mb-1">
                  <span className="flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 bg-amber-400 rounded-full animate-pulse" />
                    代码索引: {indexStatus.parsed_files ?? 0} / {indexStatus.total_files ?? "?"} 文件
                  </span>
                  <span>
                    {indexStatus.total_files
                      ? `${Math.round(((indexStatus.parsed_files ?? 0) / indexStatus.total_files) * 100)}%`
                      : ""}
                  </span>
                </div>
                <div className="h-1 bg-slate-700 rounded-full overflow-hidden">
                  {indexStatus.total_files ? (
                    <div
                      className="h-full bg-amber-400 rounded-full transition-all duration-500"
                      style={{ width: `${((indexStatus.parsed_files ?? 0) / indexStatus.total_files) * 100}%` }}
                    />
                  ) : (
                    <div className="h-full bg-amber-400/50 rounded-full animate-pulse" style={{ width: "100%" }} />
                  )}
                </div>
              </div>
            )}

            {/* 静态分析进度条 */}
            {(scan.status === "analyzing" || scan.status === "auditing") && !scan.static_analysis_done && scan.static_total_files > 0 && (
              <div>
                <div className="flex justify-between text-xs text-slate-400 mb-1">
                  <span className="flex items-center gap-1.5">
                    <span className="w-1.5 h-1.5 bg-cyan-400 rounded-full animate-pulse" />
                    静态分析: {scan.static_scanned_files} / {scan.static_total_files} 文件
                  </span>
                  <span>{scan.static_total_files > 0 ? Math.round(scan.static_scanned_files / scan.static_total_files * 100) : 0}%</span>
                </div>
                <div className="h-1 bg-slate-700 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-cyan-400 rounded-full transition-all duration-500"
                    style={{ width: `${scan.static_total_files > 0 ? (scan.static_scanned_files / scan.static_total_files * 100) : 0}%` }}
                  />
                </div>
              </div>
            )}

            {/* 静态分析完成标记 */}
            {scan.static_analysis_done && scan.status === "auditing" && (
              <div className="text-xs text-green-400 flex items-center gap-1">
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                静态分析完成
              </div>
            )}

            {fpReview && isFpReviewing && (
              <div className="text-xs text-amber-300 flex items-center gap-2 min-w-0">
                <span className="w-1.5 h-1.5 bg-amber-400 rounded-full animate-pulse shrink-0" />
                <span className="shrink-0">
                  AI复核: {fpReview.processed}/{fpReview.total}
                </span>
                {currentFpReviewTarget ? (
                  <span className="font-mono truncate text-amber-200">
                    {currentFpReviewTarget.file}:{currentFpReviewTarget.line} {currentFpReviewTarget.function}
                  </span>
                ) : (
                  <span className="text-amber-400/70">等待当前目标...</span>
                )}
              </div>
            )}

            {hasReportModeSkill && (
              <div className="text-xs text-purple-300 flex items-center gap-2 min-w-0">
                <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${isRunning ? "bg-purple-400 animate-pulse" : "bg-purple-500"}`} />
                <span className="shrink-0">
                  SKILL报告: {scan.skill_reports?.length ?? 0} 个
                </span>
                {isRunning ? (
                  <span className="text-purple-400/70">运行中，完成后同步 Markdown</span>
                ) : (
                  <span className="text-purple-400/70">已同步</span>
                )}
              </div>
            )}

            {/* LLM 审计进度条 */}
            {(scan.status === "auditing" || isDone) && (
              <div>
                <div className="flex justify-between text-xs text-slate-400 mb-1">
                  <span>
                    {scan.static_analysis_done
                      ? `${scan.processed_candidates} / ${scan.total_candidates} 候选点`
                      : `已处理 ${scan.processed_candidates} 个候选点`}
                  </span>
                  <span>{scan.static_analysis_done ? `${pct}%` : ""}</span>
                </div>
                <div className="h-1.5 bg-slate-700 rounded-full overflow-hidden">
                  {scan.static_analysis_done ? (
                    <div
                      className={`h-full rounded-full transition-all duration-500 ${isDone ? "bg-green-500" : "bg-blue-500"}`}
                      style={{ width: `${pct}%` }}
                    />
                  ) : (
                    <div className="h-full bg-blue-500/50 rounded-full animate-pulse" style={{ width: "100%" }} />
                  )}
                </div>
                {scan.current_candidate && (
                  <p className="text-xs text-slate-500 mt-1 truncate">
                    正在审计：
                    <span className="font-mono text-slate-400">
                      {scan.current_candidate.file}:{scan.current_candidate.line}
                    </span>
                    {" — "}
                    <span className="text-slate-400">{scan.current_candidate.function}</span>
                  </p>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Error */}
        {visibleErrorMessage && (
          <div className="mt-3 p-2.5 bg-red-500/10 border border-red-500/30 rounded-lg text-sm text-red-400">
            {visibleErrorMessage}
          </div>
        )}
      </div>

      {/* Main content — Results table */}
      <div className="flex-1 overflow-auto px-6 py-4">
        {scan.vulnerabilities.length === 0 && isDone ? (
          <div className="flex items-center justify-center h-64 text-slate-400">
            <div className="text-center">
              <p className="text-lg font-medium">未发现漏洞</p>
              <p className="text-sm mt-1 text-slate-500">代码看起来很安全</p>
            </div>
          </div>
        ) : (
          <VulnerabilityList
            scanId={scanId}
            vulnerabilities={scan.vulnerabilities}
            events={scan.events}
            isScanning={!!isRunning}
            currentCandidate={scan.current_candidate}
            totalCandidates={scan.total_candidates}
            processedCandidates={scan.processed_candidates}
            fpReview={fpReview}
            currentFpReviewIndex={currentFpReviewIndex}
            onFeedbackCreated={addSelectedFeedbackIds}
            onFeedbackRemoved={removeSelectedFeedbackIds}
            onVulnMarked={() => {
              if (skillOpen && skillType) {
                if (skillType === "__fp_review__") {
                  getFpReviewSkill(scanId).then(setSkillContent).catch(() => {});
                } else {
                  getSkillContent(scanId, skillType).then(setSkillContent).catch(() => {});
                }
              }
            }}
          />
        )}
      </div>

      {/* Log floating button */}
      <button
        onClick={() => { setLogOpen(true); setLastSeenEvents(logEvents.length); }}
        className="fixed bottom-6 right-6 px-4 py-2.5 bg-slate-700 hover:bg-slate-600 text-slate-300 text-sm font-medium rounded-full shadow-lg border border-slate-600 transition-colors z-40 flex items-center gap-2"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        日志
        {unseenCount > 0 && (
          <span className="bg-blue-500 text-white text-xs rounded-full px-1.5 py-0.5 min-w-[1.25rem] text-center">
            {unseenCount > 99 ? "99+" : unseenCount}
          </span>
        )}
      </button>

      {/* Log slide-over panel */}
      {logOpen && (
        <>
          {/* Backdrop */}
          <div
            className="fixed inset-0 bg-black/30 z-40"
            onClick={() => setLogOpen(false)}
          />
          {/* Panel */}
          <div className="fixed right-0 top-0 bottom-0 w-[32rem] max-w-full bg-slate-900 border-l border-slate-700 z-50 flex flex-col shadow-2xl">
            <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700">
              <h3 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">
                处理日志
              </h3>
              <button
                onClick={() => setLogOpen(false)}
                className="text-slate-500 hover:text-slate-300 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div
              ref={logRef}
              className="flex-1 overflow-y-auto p-3 space-y-1 font-mono text-xs"
            >
              {logEvents.length === 0 ? (
                <p className="text-slate-500">等待事件...</p>
              ) : (
                <>
                  {truncated && (
                    <p className="text-slate-600 text-center py-1 border-b border-slate-700/50 mb-1">
                      ... 已省略 {allLogEvents.length - MAX_LOG_LINES} 条早期日志 ...
                    </p>
                  )}
                  {logEvents.map((event, i) => (
                    <EventLine key={i} event={event} />
                  ))}
                </>
              )}
            </div>
          </div>
        </>
      )}

      {/* Feedback Manager Panel */}
      {feedbackOpen && scan.project_id && (
        <FeedbackManager
          checkers={checkers.filter((c) => scan.scan_items.includes(c.name))}
          initialTypes={scan.scan_items}
          scanId={scanId}
          projectId={scan.project_id}
          selectedIds={selectedFeedbackIds ?? new Set(scan.feedback_ids)}
          onSelectionChange={handleFeedbackChange}
          onFeedbackCreated={addSelectedFeedbackIds}
          onClose={() => setFeedbackOpen(false)}
        />
      )}

      {/* OpenCode model pool dashboard */}
      {modelPoolOpen && (
        <>
          <div
            className="fixed inset-0 bg-black/30 z-40"
            onClick={() => setModelPoolOpen(false)}
          />
          <div className="fixed right-0 top-0 bottom-0 w-[60rem] max-w-full bg-slate-900 border-l border-slate-700 z-50 flex flex-col shadow-2xl">
            <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700">
              <div>
                <h3 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">
                  OpenCode 模型看板
                </h3>
                <p className="text-xs text-slate-500 mt-1">
                  {scan.opencode_pool?.updated_at
                    ? `最后更新：${formatDateTime(scan.opencode_pool.updated_at)}`
                    : "当前扫描尚未产生 OpenCode 模型池统计"}
                </p>
              </div>
              <button
                onClick={() => setModelPoolOpen(false)}
                className="text-slate-500 hover:text-slate-300 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <ModelPoolDashboard pool={scan.opencode_pool ?? null} />
          </div>
        </>
      )}

      {/* SKILL Preview Panel */}
      {skillOpen && (
        <>
          <div
            className="fixed inset-0 bg-black/30 z-40"
            onClick={() => setSkillOpen(false)}
          />
          <div className="fixed right-0 top-0 bottom-0 w-[40rem] max-w-full bg-slate-900 border-l border-slate-700 z-50 flex flex-col shadow-2xl">
            <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700">
              <h3 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">
                SKILL 预览
              </h3>
              <button
                onClick={() => setSkillOpen(false)}
                className="text-slate-500 hover:text-slate-300 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            {/* Type tabs */}
            <div className="flex gap-1.5 px-4 py-2.5 border-b border-slate-700/50 overflow-x-auto">
              {scan.scan_items.map((item) => (
                <button
                  key={item}
                  onClick={() => loadSkill(item)}
                  className={`px-3 py-1.5 text-xs font-medium rounded-lg border transition-colors whitespace-nowrap ${
                    skillType === item
                      ? "bg-emerald-500/20 text-emerald-400 border-emerald-500/30"
                      : "text-slate-400 border-slate-700 hover:bg-slate-800"
                  }`}
                >
                  {item.toUpperCase()}
                </button>
              ))}
              <button
                onClick={() => loadFpReviewSkill()}
                className={`px-3 py-1.5 text-xs font-medium rounded-lg border transition-colors whitespace-nowrap ${
                  skillType === "__fp_review__"
                    ? "bg-amber-500/20 text-amber-400 border-amber-500/30"
                    : "text-slate-400 border-slate-700 hover:bg-slate-800"
                }`}
              >
                FP REVIEW
              </button>
            </div>
            {/* Content */}
            <div className="flex-1 overflow-y-auto p-4">
              {skillLoading ? (
                <div className="flex items-center gap-2 text-xs text-slate-500">
                  <div className="w-3 h-3 border border-slate-600 border-t-blue-400 rounded-full animate-spin" />
                  加载中...
                </div>
              ) : (
                <pre className="text-xs text-slate-400 whitespace-pre-wrap leading-relaxed font-mono">
                  {skillContent}
                </pre>
              )}
            </div>
          </div>
        </>
      )}

      {/* Markdown report panel */}
      {reportsOpen && (
        <>
          <div
            className="fixed inset-0 bg-black/30 z-40"
            onClick={() => setReportsOpen(false)}
          />
          <div className="fixed right-0 top-0 bottom-0 w-[52rem] max-w-full bg-slate-900 border-l border-slate-700 z-50 flex flex-col shadow-2xl">
            <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700">
              <div>
                <h3 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">
                  SKILL 报告
                </h3>
                <p className="text-xs text-slate-500 mt-1">
                  {isRunning ? "报告型 SKILL 正在运行或等待同步" : `已同步 ${displayedReports.length} 个 Markdown 报告`}
                </p>
              </div>
              <button
                onClick={() => setReportsOpen(false)}
                className="text-slate-500 hover:text-slate-300 transition-colors"
              >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="flex min-h-0 flex-1">
              <div className="w-64 shrink-0 border-r border-slate-800 p-3 overflow-y-auto">
                {reportsLoading ? (
                  <div className="flex items-center gap-2 text-xs text-slate-500">
                    <div className="w-3 h-3 border border-slate-600 border-t-purple-400 rounded-full animate-spin" />
                    加载中...
                  </div>
                ) : displayedReports.length === 0 ? (
                  <div className="rounded border border-slate-800 bg-slate-950 px-3 py-4 text-xs text-slate-500">
                    暂无报告
                  </div>
                ) : (
                  <div className="space-y-2">
                    {displayedReports.map((report, index) => (
                      <button
                        key={`${report.checker_name}-${report.filename}-${index}`}
                        onClick={() => setActiveReportIndex(index)}
                        className={`w-full rounded-lg border px-3 py-2 text-left transition-colors ${
                          index === activeReportIndex
                            ? "border-purple-500/50 bg-purple-500/10"
                            : "border-slate-800 bg-slate-950 hover:border-slate-700"
                        }`}
                      >
                        <div className="text-xs font-semibold text-slate-200 truncate">{report.title || report.filename}</div>
                        <div className="mt-1 text-[11px] text-slate-500 font-mono truncate">{report.checker_name}/{report.filename}</div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
              <div className="min-w-0 flex-1 overflow-y-auto p-5">
                {activeReport ? (
                  <MarkdownContent content={activeReport.content} />
                ) : (
                  <div className="text-sm text-slate-500">选择左侧报告查看内容</div>
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function EventLine({ event }: { event: ScanEvent }) {
  const time = new Date(event.timestamp).toLocaleTimeString();

  const phaseColor: Record<string, string> = {
    init: "text-yellow-400",
    mcp_ready: "text-green-400",
    static_analysis: "text-cyan-400",
    auditing: "text-blue-400",
    opencode_output: "text-slate-500",
    complete: "text-green-400",
    error: "text-red-400",
  };

  return (
    <div className="flex gap-2 leading-5">
      <span className="text-slate-600 shrink-0">{time}</span>
      <span className={`shrink-0 ${phaseColor[event.phase] ?? "text-slate-400"}`}>
        [{event.phase}]
      </span>
      <span className="text-slate-400 break-all">{event.message}</span>
    </div>
  );
}

function ModelPoolDashboard({ pool }: { pool: OpenCodePoolStatus | null }) {
  const models = pool?.models ?? [];
  const total = models.reduce((sum, item) => sum + item.total, 0);
  const success = models.reduce((sum, item) => sum + item.success, 0);
  const failure = models.reduce((sum, item) => sum + item.failure, 0);
  const timeout = models.reduce((sum, item) => sum + item.timeout, 0);
  const cancelled = models.reduce((sum, item) => sum + item.cancelled, 0);

  if (!pool || models.length === 0) {
    return (
      <div className="flex-1 overflow-y-auto p-5">
        <div className="rounded-lg border border-slate-800 bg-slate-950 px-4 py-5 text-sm text-slate-500">
          当前扫描尚未产生 OpenCode 模型池统计。开始运行审计、扫描前内存 API 识别或 AI 去误报后，这里会显示模型分配情况。
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-5 space-y-4">
      <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
        <MetricBox label="运行中" value={pool.global_running} tone="cyan" />
        <MetricBox label="排队中" value={pool.global_queued} tone="amber" />
        <MetricBox label="累计任务" value={total} />
        <MetricBox label="成功" value={success} tone="green" />
        <MetricBox label="失败" value={failure} tone="red" />
        <MetricBox label="超时/取消" value={timeout + cancelled} tone="amber" />
      </div>

      <div className="overflow-x-auto rounded-lg border border-slate-800">
        <table className="w-full min-w-[56rem] text-sm">
          <thead className="bg-slate-950">
            <tr>
              <th className={thCls}>模型</th>
              <th className={thCls}>能力</th>
              <th className={thCls}>权重</th>
              <th className={thCls}>运行/上限</th>
              <th className={thCls}>排队</th>
              <th className={thCls}>累计</th>
              <th className={thCls}>成功</th>
              <th className={thCls}>失败</th>
              <th className={thCls}>超时</th>
              <th className={thCls}>取消</th>
              <th className={thCls}>平均耗时</th>
              <th className={thCls}>最近状态</th>
            </tr>
          </thead>
          <tbody>
            {models.map((model) => (
              <tr key={model.id} className="border-t border-slate-800/70">
                <td className={tdCls}>
                  <div className="font-semibold text-slate-100">{model.id}</div>
                  <div className="mt-1 max-w-48 truncate font-mono text-[11px] text-slate-500">
                    {model.model || "(默认模型)"}
                  </div>
                </td>
                <td className={tdCls}>{capabilityLabel(model.capability)}</td>
                <td className={tdCls}>{model.weight}</td>
                <td className={tdCls}>{model.running}/{model.max_concurrency}</td>
                <td className={tdCls}>{model.queued}</td>
                <td className={tdCls}>{model.total}</td>
                <td className={`${tdCls} text-green-300`}>{model.success}</td>
                <td className={`${tdCls} text-red-300`}>{model.failure}</td>
                <td className={`${tdCls} text-amber-300`}>{model.timeout}</td>
                <td className={`${tdCls} text-slate-300`}>{model.cancelled}</td>
                <td className={tdCls}>{formatDuration(model.avg_duration_seconds)}</td>
                <td className={tdCls}>
                  <div className={statusClass(model.last_status)}>
                    {statusLabel(model.last_status)}
                  </div>
                  <div className="mt-1 text-[11px] text-slate-600">
                    {formatDateTime(model.last_finished_at || model.last_started_at)}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

const thCls = "px-3 py-2 text-left text-xs font-semibold text-slate-400";
const tdCls = "px-3 py-3 text-slate-300 align-top";

function MetricBox({
  label,
  value,
  tone = "slate",
}: {
  label: string;
  value: number;
  tone?: "slate" | "cyan" | "amber" | "green" | "red";
}) {
  const color = {
    slate: "text-slate-100",
    cyan: "text-cyan-300",
    amber: "text-amber-300",
    green: "text-green-300",
    red: "text-red-300",
  }[tone];
  return (
    <div className="rounded-lg border border-slate-800 bg-slate-950 px-3 py-3">
      <div className="text-xs text-slate-500">{label}</div>
      <div className={`mt-1 text-xl font-semibold ${color}`}>{value}</div>
    </div>
  );
}

function capabilityLabel(value: string): string {
  if (value === "high") return "高";
  if (value === "medium") return "中";
  if (value === "low") return "低";
  return value || "-";
}

function statusLabel(value: string): string {
  if (value === "queued") return "排队";
  if (value === "running") return "运行中";
  if (value === "success") return "成功";
  if (value === "failure") return "失败";
  if (value === "timeout") return "超时";
  if (value === "cancelled") return "取消";
  return value || "-";
}

function statusClass(value: string): string {
  const base = "inline-flex rounded border px-2 py-0.5 text-xs";
  if (value === "running") return `${base} border-cyan-500/30 bg-cyan-500/10 text-cyan-300`;
  if (value === "success") return `${base} border-green-500/30 bg-green-500/10 text-green-300`;
  if (value === "failure") return `${base} border-red-500/30 bg-red-500/10 text-red-300`;
  if (value === "timeout" || value === "queued") return `${base} border-amber-500/30 bg-amber-500/10 text-amber-300`;
  return `${base} border-slate-700 bg-slate-800 text-slate-400`;
}

function formatDuration(seconds: number): string {
  if (!seconds || seconds <= 0) return "-";
  if (seconds < 60) return `${seconds.toFixed(1)}s`;
  const minutes = Math.floor(seconds / 60);
  const rest = Math.round(seconds % 60);
  return `${minutes}m ${rest}s`;
}

function formatDateTime(value: string): string {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleString();
}

function MarkdownContent({ content }: { content: string }) {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        h1: ({ children }) => <h1 className="mb-4 text-xl font-semibold text-white">{children}</h1>,
        h2: ({ children }) => <h2 className="mt-6 mb-2 text-base font-semibold text-purple-100">{children}</h2>,
        h3: ({ children }) => <h3 className="mt-4 mb-2 text-sm font-semibold text-slate-100">{children}</h3>,
        p: ({ children }) => <p className="my-2 text-sm leading-7 text-slate-300">{children}</p>,
        ul: ({ children }) => <ul className="my-2 list-disc space-y-1 pl-5 text-sm leading-relaxed text-slate-300 marker:text-purple-400">{children}</ul>,
        ol: ({ children }) => <ol className="my-2 list-decimal space-y-1 pl-5 text-sm leading-relaxed text-slate-300 marker:text-purple-400">{children}</ol>,
        li: ({ children }) => <li>{children}</li>,
        table: ({ children }) => (
          <div className="my-3 overflow-x-auto rounded-lg border border-slate-800">
            <table className="w-full min-w-max text-sm">{children}</table>
          </div>
        ),
        thead: ({ children }) => <thead className="bg-slate-950">{children}</thead>,
        th: ({ children }) => <th className="border-b border-slate-800 px-3 py-2 text-left text-xs font-semibold text-slate-400">{children}</th>,
        tr: ({ children }) => <tr className="border-t border-slate-800/70 first:border-t-0">{children}</tr>,
        td: ({ children }) => <td className="px-3 py-2 text-slate-300">{children}</td>,
        pre: ({ children }) => (
          <pre className="my-3 overflow-x-auto rounded-lg border border-slate-700 bg-slate-950 p-4 text-xs leading-relaxed text-slate-300 [&_code]:border-0 [&_code]:bg-transparent [&_code]:p-0 [&_code]:text-slate-300">
            {children}
          </pre>
        ),
        code: ({ className, children }) => (
          <code className={`${className ?? ""} rounded border border-slate-700 bg-slate-950 px-1.5 py-0.5 text-[0.85em] text-purple-200`}>
            {children}
          </code>
        ),
        strong: ({ children }) => <strong className="font-semibold text-slate-100">{children}</strong>,
      }}
    >
      {content}
    </ReactMarkdown>
  );
}
